pretrained_base_model_path: './model_weights/sd-image-variations-diffusers'
pretrained_vae_path: './model_weights/sd-vae-ft-mse'
image_encoder_path: './model_weights/image_encoder'



denoising_unet_path: "./model_weights/MusePose/denoising_unet.pth"
reference_unet_path: "./model_weights/MusePose/reference_unet.pth"
pose_guider_path: "./model_weights/MusePose/pose_guider.pth"
motion_module_path: "./model_weights/MusePose/motion_module.pth"



inference_config: "./repos/musepose/configs/inference_v2.yaml"
weight_dtype: 'fp16'



test_cases:
  "./assets/images/kunkun.jpg":
    - "./assets/poses/align/align_pose_tmp.mp4"
